# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"


# : File-specific styles {{{

[filetype]
rules = [
	# archive
	{ name = "*.{zip,rar,7z*,iso,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*,bin,img,tgz}", fg = "#FFC038" },
	# video
	{ name = "*.{3gp,avif,avi,m4v,mkv,mov,mp4,mts,webm,wmv}", fg = "#FF64CE" },

	# audio
	{ name = "*.{aac,flac,m4a,mp3,ogg,wav}", fg = "#FF3845" },

	# exec
	{ name = "*.{apk,app,exe,sh,applescript,dmg,bash,bat}", fg = "#93C039" },

	# text
	{ name = "*.{lua,conf,py,vimrc,zshrc,vimrc,gitconfig,c,c++,cfg,cp,cpp,cppm,cpy,css,ts,diff,env*,mjs,gitignore*,vim*,info,ini,js,json,json5,jsx,log,m3u,m3u8,md,nfo,php,pls,srt,toml,ts,tsconfig,tsx,txt,typoscript,xml,yaml,yml}", fg = "#ECF6F8" },

	# image
	{ name = "*.{bmp,ico,gif,jpeg,jpg,png,webp}", fg = "#FF8E38" },

	# editable graphic
	{ name = "*.{otf,psd,svg,svgz,ttf,woff,woff2,heic,arw,raw,dng}", fg = "#FF7A83" },

	# database
	{ name = "*.{db,dll,git,sql,sqlite,sqlite3,csv}", fg = "#DAD8F1" },

	# document
	{ name = "*.{doc,docx,ebook,epub,htm,html,mobi,pdf,ppt,pptx,xls,xlsx}", fg = "#57B1C1" },

]

# : }}}

[flavor]
dark = "everforest-medium"
light = "everforest-medium"

[tabs]
active   = { fg = "#3d484d", bg = "#7fbbb3", bold = true }

# : Icons {{{

[icon]
globs = []
dirs  = [
	{ name = ".config", text = "î—¼" },
	{ name = ".git", text = "î—»" },
	{ name = ".github", text = "î—½" },
	{ name = ".npm", text = "î—º" },
	{ name = "Desktop", text = "ï„ˆ" },
	{ name = "Development", text = "îœŒ" },
	{ name = "Documents", text = "ï" },
	{ name = "Downloads", text = "ï’˜" },
	{ name = "Library", text = "î®œ" },
	{ name = "Movies", text = "ï‘‡" },
	{ name = "Music", text = "ï€¥" },
	{ name = "Pictures", text = "î‰„" },
	{ name = "Public", text = "ï«" },
	{ name = "Videos", text = "ï‘‡" },
]
files = [
	{ name = ".babelrc", text = "î˜¹", fg = "#cbcb41" },
	{ name = ".bash_profile", text = "î˜•", fg = "#89e051" },
	{ name = ".bashrc", text = "î˜•", fg = "#89e051" },
	{ name = ".clang-format", text = "î˜•", fg = "#6d8086" },
	{ name = ".clang-tidy", text = "î˜•", fg = "#6d8086" },
	{ name = ".codespellrc", text = "ó°“†", fg = "#35da60" },
	{ name = ".condarc", text = "îœ•", fg = "#43b02a" },
	{ name = ".dockerignore", text = "ó°¡¨", fg = "#458ee6" },
	{ name = ".ds_store", text = "î˜•", fg = "#41535b" },
	{ name = ".editorconfig", text = "î™’", fg = "#fff2f2" },
	{ name = ".env", text = "ï‘¢", fg = "#faf743" },
	{ name = ".eslintignore", text = "î™•", fg = "#4b32c3" },
	{ name = ".eslintrc", text = "î™•", fg = "#4b32c3" },
	{ name = ".git-blame-ignore-revs", text = "îœ‚", fg = "#f54d27" },
	{ name = ".gitattributes", text = "îœ‚", fg = "#f54d27" },
	{ name = ".gitconfig", text = "î˜•", fg = "#f54d27" },
	{ name = ".gitignore", text = "îœ‚", fg = "#f54d27" },
	{ name = ".gitlab-ci.yml", text = "ïŠ–", fg = "#e24329" },
	{ name = ".gitmodules", text = "îœ‚", fg = "#f54d27" },
	{ name = ".gtkrc-2.0", text = "ï¢", fg = "#ffffff" },
	{ name = ".gvimrc", text = "î˜«", fg = "#019833" },
	{ name = ".justfile", text = "ï‚­", fg = "#6d8086" },
	{ name = ".luacheckrc", text = "î˜•", fg = "#00a2ff" },
	{ name = ".luaurc", text = "î˜•", fg = "#00a2ff" },
	{ name = ".mailmap", text = "ó°Š¢", fg = "#f54d27" },
	{ name = ".nanorc", text = "î ¸", fg = "#440077" },
	{ name = ".npmignore", text = "îœ", fg = "#e8274b" },
	{ name = ".npmrc", text = "îœ", fg = "#e8274b" },
	{ name = ".nuxtrc", text = "ó±„†", fg = "#00c58e" },
	{ name = ".nvmrc", text = "îœ˜", fg = "#5fa04e" },
	{ name = ".pre-commit-config.yaml", text = "ó°›¢", fg = "#f8b424" },
	{ name = ".prettierignore", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc.cjs", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc.js", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc.json", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc.json5", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc.mjs", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc.toml", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc.yaml", text = "îš´", fg = "#4285f4" },
	{ name = ".prettierrc.yml", text = "îš´", fg = "#4285f4" },
	{ name = ".pylintrc", text = "î˜•", fg = "#6d8086" },
	{ name = ".settings.json", text = "îœŒ", fg = "#854cc7" },
	{ name = ".SRCINFO", text = "ó°£‡", fg = "#0f94d2" },
	{ name = ".vimrc", text = "î˜«", fg = "#019833" },
	{ name = ".Xauthority", text = "ï©", fg = "#e54d18" },
	{ name = ".xinitrc", text = "ï©", fg = "#e54d18" },
	{ name = ".Xresources", text = "ï©", fg = "#e54d18" },
	{ name = ".xsession", text = "ï©", fg = "#e54d18" },
	{ name = ".zprofile", text = "î˜•", fg = "#89e051" },
	{ name = ".zshenv", text = "î˜•", fg = "#89e051" },
	{ name = ".zshrc", text = "î˜•", fg = "#89e051" },
	{ name = "_gvimrc", text = "î˜«", fg = "#019833" },
	{ name = "_vimrc", text = "î˜«", fg = "#019833" },
	{ name = "AUTHORS", text = "î·Š", fg = "#a172ff" },
	{ name = "AUTHORS.txt", text = "î·Š", fg = "#a172ff" },
	{ name = "brewfile", text = "î‘", fg = "#701516" },
	{ name = "bspwmrc", text = "ï•", fg = "#2f2f2f" },
	{ name = "build", text = "î˜º", fg = "#89e051" },
	{ name = "build.gradle", text = "î™ ", fg = "#005f87" },
	{ name = "build.zig.zon", text = "îš©", fg = "#f69a1b" },
	{ name = "bun.lock", text = "î¯", fg = "#eadcd1" },
	{ name = "bun.lockb", text = "î¯", fg = "#eadcd1" },
	{ name = "cantorrc", text = "ï³", fg = "#1c99f3" },
	{ name = "checkhealth", text = "ó°“™", fg = "#75b4fb" },
	{ name = "cmakelists.txt", text = "î”", fg = "#dce3eb" },
	{ name = "code_of_conduct", text = "ï’®", fg = "#e41662" },
	{ name = "code_of_conduct.md", text = "ï’®", fg = "#e41662" },
	{ name = "commit_editmsg", text = "îœ‚", fg = "#f54d27" },
	{ name = "commitlint.config.js", text = "ó°œ˜", fg = "#2b9689" },
	{ name = "commitlint.config.ts", text = "ó°œ˜", fg = "#2b9689" },
	{ name = "compose.yaml", text = "ó°¡¨", fg = "#458ee6" },
	{ name = "compose.yml", text = "ó°¡¨", fg = "#458ee6" },
	{ name = "config", text = "î˜•", fg = "#6d8086" },
	{ name = "containerfile", text = "ó°¡¨", fg = "#458ee6" },
	{ name = "copying", text = "î˜Š", fg = "#cbcb41" },
	{ name = "copying.lesser", text = "î˜Š", fg = "#cbcb41" },
	{ name = "Directory.Build.props", text = "î˜•", fg = "#00a2ff" },
	{ name = "Directory.Build.targets", text = "î˜•", fg = "#00a2ff" },
	{ name = "Directory.Packages.props", text = "î˜•", fg = "#00a2ff" },
	{ name = "docker-compose.yaml", text = "ó°¡¨", fg = "#458ee6" },
	{ name = "docker-compose.yml", text = "ó°¡¨", fg = "#458ee6" },
	{ name = "dockerfile", text = "ó°¡¨", fg = "#458ee6" },
	{ name = "eslint.config.cjs", text = "î™•", fg = "#4b32c3" },
	{ name = "eslint.config.js", text = "î™•", fg = "#4b32c3" },
	{ name = "eslint.config.mjs", text = "î™•", fg = "#4b32c3" },
	{ name = "eslint.config.ts", text = "î™•", fg = "#4b32c3" },
	{ name = "ext_typoscript_setup.txt", text = "î²", fg = "#ff8700" },
	{ name = "favicon.ico", text = "î˜£", fg = "#cbcb41" },
	{ name = "fp-info-cache", text = "ïŒ", fg = "#ffffff" },
	{ name = "fp-lib-table", text = "ïŒ", fg = "#ffffff" },
	{ name = "FreeCAD.conf", text = "ïŒ¶", fg = "#cb333b" },
	{ name = "Gemfile", text = "î‘", fg = "#701516" },
	{ name = "gnumakefile", text = "î¹", fg = "#6d8086" },
	{ name = "go.mod", text = "î˜§", fg = "#00add8" },
	{ name = "go.sum", text = "î˜§", fg = "#00add8" },
	{ name = "go.work", text = "î˜§", fg = "#00add8" },
	{ name = "gradle-wrapper.properties", text = "î™ ", fg = "#005f87" },
	{ name = "gradle.properties", text = "î™ ", fg = "#005f87" },
	{ name = "gradlew", text = "î™ ", fg = "#005f87" },
	{ name = "groovy", text = "îµ", fg = "#4a687c" },
	{ name = "gruntfile.babel.js", text = "î˜‘", fg = "#e37933" },
	{ name = "gruntfile.coffee", text = "î˜‘", fg = "#e37933" },
	{ name = "gruntfile.js", text = "î˜‘", fg = "#e37933" },
	{ name = "gruntfile.ts", text = "î˜‘", fg = "#e37933" },
	{ name = "gtkrc", text = "ï¢", fg = "#ffffff" },
	{ name = "gulpfile.babel.js", text = "î˜", fg = "#cc3e44" },
	{ name = "gulpfile.coffee", text = "î˜", fg = "#cc3e44" },
	{ name = "gulpfile.js", text = "î˜", fg = "#cc3e44" },
	{ name = "gulpfile.ts", text = "î˜", fg = "#cc3e44" },
	{ name = "hypridle.conf", text = "ï™", fg = "#00aaae" },
	{ name = "hyprland.conf", text = "ï™", fg = "#00aaae" },
	{ name = "hyprlandd.conf", text = "ï™", fg = "#00aaae" },
	{ name = "hyprlock.conf", text = "ï™", fg = "#00aaae" },
	{ name = "hyprpaper.conf", text = "ï™", fg = "#00aaae" },
	{ name = "i18n.config.js", text = "ó°—Š", fg = "#7986cb" },
	{ name = "i18n.config.ts", text = "ó°—Š", fg = "#7986cb" },
	{ name = "i3blocks.conf", text = "ïš", fg = "#e8ebee" },
	{ name = "i3status.conf", text = "ïš", fg = "#e8ebee" },
	{ name = "index.theme", text = "î¹²", fg = "#2db96f" },
	{ name = "ionic.config.json", text = "î©", fg = "#4f8ff7" },
	{ name = "justfile", text = "ï‚­", fg = "#6d8086" },
	{ name = "kalgebrarc", text = "ï³", fg = "#1c99f3" },
	{ name = "kdeglobals", text = "ï³", fg = "#1c99f3" },
	{ name = "kdenlive-layoutsrc", text = "ïŒ¼", fg = "#83b8f2" },
	{ name = "kdenliverc", text = "ïŒ¼", fg = "#83b8f2" },
	{ name = "kritadisplayrc", text = "ïŒ½", fg = "#f245fb" },
	{ name = "kritarc", text = "ïŒ½", fg = "#f245fb" },
	{ name = "license", text = "î˜Š", fg = "#d0bf41" },
	{ name = "license.md", text = "î˜Š", fg = "#d0bf41" },
	{ name = "lxde-rc.xml", text = "ï£", fg = "#909090" },
	{ name = "lxqt.conf", text = "ï¤", fg = "#0192d3" },
	{ name = "makefile", text = "î¹", fg = "#6d8086" },
	{ name = "mix.lock", text = "î˜­", fg = "#a074c4" },
	{ name = "mpv.conf", text = "ï®", fg = "#3b1342" },
	{ name = "node_modules", text = "îœ˜", fg = "#e8274b" },
	{ name = "nuxt.config.cjs", text = "ó±„†", fg = "#00c58e" },
	{ name = "nuxt.config.js", text = "ó±„†", fg = "#00c58e" },
	{ name = "nuxt.config.mjs", text = "ó±„†", fg = "#00c58e" },
	{ name = "nuxt.config.ts", text = "ó±„†", fg = "#00c58e" },
	{ name = "package-lock.json", text = "îœ", fg = "#7a0d21" },
	{ name = "package.json", text = "îœ", fg = "#e8274b" },
	{ name = "PKGBUILD", text = "ïŒƒ", fg = "#0f94d2" },
	{ name = "platformio.ini", text = "îš‚", fg = "#f6822b" },
	{ name = "pom.xml", text = "î™´", fg = "#7a0d21" },
	{ name = "prettier.config.cjs", text = "îš´", fg = "#4285f4" },
	{ name = "prettier.config.js", text = "îš´", fg = "#4285f4" },
	{ name = "prettier.config.mjs", text = "îš´", fg = "#4285f4" },
	{ name = "prettier.config.ts", text = "îš´", fg = "#4285f4" },
	{ name = "procfile", text = "î˜‡", fg = "#a074c4" },
	{ name = "PrusaSlicer.ini", text = "ï‘", fg = "#ec6b23" },
	{ name = "PrusaSlicerGcodeViewer.ini", text = "ï‘", fg = "#ec6b23" },
	{ name = "py.typed", text = "î˜†", fg = "#ffbc03" },
	{ name = "QtProject.conf", text = "ïµ", fg = "#40cd52" },
	{ name = "rakefile", text = "î‘", fg = "#701516" },
	{ name = "readme", text = "ó°‚º", fg = "#ededed" },
	{ name = "readme.md", text = "ó°‚º", fg = "#ededed" },
	{ name = "rmd", text = "î˜‰", fg = "#519aba" },
	{ name = "robots.txt", text = "ó°š©", fg = "#5d7096" },
	{ name = "security", text = "ó°’ƒ", fg = "#bec4c9" },
	{ name = "security.md", text = "ó°’ƒ", fg = "#bec4c9" },
	{ name = "settings.gradle", text = "î™ ", fg = "#005f87" },
	{ name = "svelte.config.js", text = "îš—", fg = "#ff3e00" },
	{ name = "sxhkdrc", text = "ï•", fg = "#2f2f2f" },
	{ name = "sym-lib-table", text = "ïŒ", fg = "#ffffff" },
	{ name = "tailwind.config.js", text = "ó±¿", fg = "#20c2e3" },
	{ name = "tailwind.config.mjs", text = "ó±¿", fg = "#20c2e3" },
	{ name = "tailwind.config.ts", text = "ó±¿", fg = "#20c2e3" },
	{ name = "tmux.conf", text = "î¯ˆ", fg = "#14ba19" },
	{ name = "tmux.conf.local", text = "î¯ˆ", fg = "#14ba19" },
	{ name = "tsconfig.json", text = "îš", fg = "#519aba" },
	{ name = "unlicense", text = "î˜Š", fg = "#d0bf41" },
	{ name = "vagrantfile", text = "ïŠ¸", fg = "#1563ff" },
	{ name = "vercel.json", text = "î£“", fg = "#ffffff" },
	{ name = "vlcrc", text = "ó°•¼", fg = "#ee7a00" },
	{ name = "webpack", text = "ó°œ«", fg = "#519aba" },
	{ name = "weston.ini", text = "ï§", fg = "#ffbb01" },
	{ name = "workspace", text = "î˜º", fg = "#89e051" },
	{ name = "wrangler.jsonc", text = "î’", fg = "#f48120" },
	{ name = "wrangler.toml", text = "î’", fg = "#f48120" },
	{ name = "xmobarrc", text = "ï", fg = "#fd4d5d" },
	{ name = "xmobarrc.hs", text = "ï", fg = "#fd4d5d" },
	{ name = "xmonad.hs", text = "ï", fg = "#fd4d5d" },
	{ name = "xorg.conf", text = "ï©", fg = "#e54d18" },
	{ name = "xsettingsd.conf", text = "ï©", fg = "#e54d18" },
]
exts = [
	# video
	{ name = "3gp", text = "îšŸ", fg = "#FF38C0" },
	{ name = "avif", text = "î˜", fg = "#FF38C0" },
	{ name = "m4v", text = "îšŸ", fg = "#FF38C0" },
	{ name = "mkv", text = "îšŸ", fg = "#FF38C0" },
	{ name = "mov", text = "îšŸ", fg = "#FF38C0" },
	{ name = "mp4", text = "îšŸ", fg = "#FF38C0" },
	{ name = "mts", text = "î˜¨", fg = "#FF38C0" },
	{ name = "webm", text = "îšŸ", fg = "#FF38C0" },
	{ name = "wmv", text = "îšŸ", fg = "#FF38C0" },

	# archive
	{ name = "7z", text = "ï", fg = "#FFC038" },
	{ name = "zip", text = "ï", fg = "#FF38C0" },
	{ name = "bin", text = "î«¨", fg = "#FFC038" },
	{ name = "img", text = "î‰±", fg = "#FFC038" },
	{ name = "rar", text = "ï", fg = "#FFC038" },
	{ name = "tgz", text = "ï", fg = "#FFC038" },

	# audio
	{ name = "aac", text = "ï€", fg = "#FF3845" },
	{ name = "flac", text = "ï€", fg = "#FF3845" },
	{ name = "m4a", text = "ï€", fg = "#FF3845" },
	{ name = "mp3", text = "ï€", fg = "#FF3845" },
	{ name = "ogg", text = "ï€", fg = "#FF3845" },
	{ name = "wav", text = "ï€", fg = "#FF3845" },

	# exec
	{ name = "apk", text = "îœ", fg = "#93C039" },
	{ name = "app", text = "î«¨", fg = "#93C039" },
	{ name = "exe", text = "î«¨", fg = "#93C039" },
	{ name = "sh", text = "î•", fg = "#93C039" },
	{ name = "applescript", text = "ï…¹", fg = "#93C039" },
	{ name = "bash", text = "î•", fg = "#93C039" },
	{ name = "bat", text = "î˜•", fg = "#93C039" },

	# text
	{ name = "c", text = "î˜", fg = "#73727e" },
	{ name = "c++", text = "î˜", fg = "#73727e" },
	{ name = "cfg", text = "î˜•", fg = "#73727e" },
	{ name = "cp", text = "î˜", fg = "#73727e" },
	{ name = "cpp", text = "î˜", fg = "#73727e" },
	{ name = "cppm", text = "î˜", fg = "#73727e" },
	{ name = "cpy", text = "ï£", fg = "#73727e" },
	{ name = "css", text = "îš¸", fg = "#73727e" },
	{ name = "ts", text = "î˜¨", fg = "#73727e" },
	{ name = "diff", text = "îœ¨", fg = "#73727e" },
	{ name = "env", text = "ï‘¢", fg = "#73727e" },
	{ name = "info", text = "ï„©", fg = "#73727e" },
	{ name = "ini", text = "î˜•", fg = "#73727e" },
	{ name = "js", text = "î˜Œ", fg = "#73727e" },
	{ name = "json", text = "î˜‹", fg = "#73727e" },
	{ name = "json5", text = "î˜‹", fg = "#73727e" },
	{ name = "jsx", text = "î˜¥", fg = "#73727e" },
	{ name = "log", text = "ó°Œ±", fg = "#73727e" },
	{ name = "m3u", text = "ó°²¹", fg = "#73727e" },
	{ name = "m3u8", text = "ó°²¹", fg = "#73727e" },
	{ name = "md", text = "ï’Š", fg = "#73727e" },
	{ name = "nfo", text = "ï„©", fg = "#73727e" },
	{ name = "php", text = "î˜ˆ", fg = "#73727e" },
	{ name = "pls", text = "ó°²¹", fg = "#73727e" },
	{ name = "srt", text = "ó°¨–", fg = "#73727e" },
	{ name = "toml", text = "îš²", fg = "#73727e" },
	{ name = "ts", text = "î˜¨", fg = "#73727e" },
	{ name = "tsconfig", text = "î²", fg = "#73727e" },
	{ name = "tsx", text = "îº", fg = "#73727e" },
	{ name = "txt", text = "ó°ˆ™", fg = "#73727e" },
	{ name = "typoscript", text = "î²", fg = "#73727e" },
	{ name = "xml", text = "ó°—€", fg = "#73727e" },
	{ name = "yaml", text = "î˜•", fg = "#73727e" },
	{ name = "yml", text = "î˜•", fg = "#73727e" },

	# image
	{ name = "bmp", text = "î˜", fg = "#FF8E38" },
	{ name = "ico", text = "î˜", fg = "#FF8E38" },
	{ name = "gif", text = "î˜", fg = "#FF8E38" },
	{ name = "jpeg", text = "î˜", fg = "#FF8E38" },
	{ name = "jpg", text = "î˜", fg = "#FF8E38" },
	{ name = "png", text = "î˜", fg = "#FF8E38" },
	{ name = "webp", text = "î˜", fg = "#FF8E38" },

	# editable graphic
	{ name = "otf", text = "ï€±", fg = "#FF7A83" },
	{ name = "psd", text = "î¸", fg = "#FF7A83" },
	{ name = "svg", text = "ó°œ¡", fg = "#FF7A83" },
	{ name = "svgz", text = "ó°œ¡", fg = "#FF7A83" },
	{ name = "ttf", text = "ï€±", fg = "#FF7A83" },
	{ name = "woff", text = "ï€±", fg = "#FF7A83" },
	{ name = "woff2", text = "ï€±", fg = "#FF7A83" },

	# database
	{ name = "db", text = "îœ†", fg = "#DAD8F1" },
	{ name = "dll", text = "î®œ", fg = "#DAD8F1" },
	{ name = "git", text = "îœ‚", fg = "#DAD8F1" },
	{ name = "sql", text = "îœ†", fg = "#DAD8F1" },
	{ name = "sqlite", text = "îœ†", fg = "#DAD8F1" },
	{ name = "sqlite3", text = "îœ†", fg = "#DAD8F1" },

	# document
	{ name = "doc", text = "ó°ˆ¬", fg = "#57B1C1" },
	{ name = "docx", text = "ó°ˆ¬", fg = "#57B1C1" },
	{ name = "ebook", text = "îŠ‹", fg = "#57B1C1" },
	{ name = "epub", text = "îŠ‹", fg = "#57B1C1" },
	{ name = "htm", text = "î˜", fg = "#57B1C1" },
	{ name = "html", text = "îœ¶", fg = "#57B1C1" },
	{ name = "mobi", text = "îŠ‹", fg = "#57B1C1" },
	{ name = "pdf", text = "î««", fg = "#57B1C1" },
	{ name = "ppt", text = "ó°ˆ§", fg = "#57B1C1" },
	{ name = "pptx", text = "ó°ˆ§", fg = "#57B1C1" },
	{ name = "xls", text = "ó°ˆ›", fg = "#57B1C1" },
	{ name = "xlsx", text = "ó°ˆ›", fg = "#57B1C1" },

	{ name = "ğŸ”¥", text = "ï­", fg = "#ff4c1f" },
]
conds = [
	# Special files
	{ if = "orphan", text = "ï±" },
	{ if = "link", text = "ï’" },
	{ if = "block", text = "ïƒ‰" },
	{ if = "char", text = "ï‡€" },
	{ if = "fifo", text = "ï‡‘" },
	{ if = "sock", text = "ï‡¤" },
	{ if = "sticky", text = "ï‡¼" },
	{ if = "dummy", text = "ï—" },

	# Fallback
	{ if = "dir", text = "î—¿" },
	{ if = "exec", text = "ï’‰" },
	{ if = "!dir", text = "ï…›" },
]

# : }}}
